config/routes.rb
Rails.application.routes.draw do
  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :movie, :composer, :singer, :lyricist, :year, :language, :raaga)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raaganveshana</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="hero-unit text-center">Raagas in Indian Film Music</div>

<%= yield %>

  
  <div class="footer text-center">
	<p>&copy; 808Labs 2014</p>
  </div>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :movie, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :movie, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :composer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :composer, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :singer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :singer, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lyricist, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lyricist, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :language, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :language, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :raaga, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :raaga, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                songs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/index.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:movie) %></th>
      <th><%= model_class.human_attribute_name(:composer) %></th>
      <th><%= model_class.human_attribute_name(:singer) %></th>
      <th><%= model_class.human_attribute_name(:lyricist) %></th>
      <th><%= model_class.human_attribute_name(:year) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:raaga) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.id, song_path(song) %></td>
        <td><%= song.title %></td>
        <td><%= song.movie %></td>
        <td><%= song.composer %></td>
        <td><%= song.singer %></td>
        <td><%= song.lyricist %></td>
        <td><%= song.year %></td>
        <td><%= song.language %></td>
        <td><%= song.raaga %></td>
        <td><%=l song.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_song_path(song), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      song_path(song),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_song_path,
            :class => 'btn btn-primary' %>

app/views/songs/new.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/show.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @song.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:movie) %>:</strong></dt>
  <dd><%= @song.movie %></dd>
  <dt><strong><%= model_class.human_attribute_name(:composer) %>:</strong></dt>
  <dd><%= @song.composer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:singer) %>:</strong></dt>
  <dd><%= @song.singer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lyricist) %>:</strong></dt>
  <dd><%= @song.lyricist %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @song.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @song.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:raaga) %>:</strong></dt>
  <dd><%= @song.raaga %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              songs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_song_path(@song), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              song_path(@song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>